INSERT INTO USERS (username, password) VALUES ('sarah1', '$2a$10$1VWQBQGgFurYEeMvFT2NDem.Gt2rU/wqyiBraRCJOCRaxPFn6IlUi');
INSERT INTO USERS (username, password) VALUES ('kumar2', '$2a$10$gczTpZhqeVTfgjjVYG.Qye5RdWzqFz7yV1v4XGixC20CpJEOm8iWG');
INSERT INTO USERS (username, password) VALUES ('hank-owns-no-cards', '$2a$10$StBWRDuQcOS99d1EozrOCeUbdRZ7lDNPmbUMKyjJZl2qioeEyoM1q');

INSERT INTO CASH_CARDS(ID, AMOUNT, OWNER) VALUES (99, 123.45, 'sarah1');
INSERT INTO CASH_CARDS(ID, AMOUNT, OWNER) VALUES (100, 1.00, 'sarah1');
INSERT INTO CASH_CARDS(ID, AMOUNT, OWNER) VALUES (101, 150.00, 'sarah1');
INSERT INTO CASH_CARDS(ID, AMOUNT, OWNER) VALUES (102, 200.00, 'kumar2');